Build Gecko in 4 threads only
The F-Droid build server runs compilation in 20 threads, I suspect this
may trigger those weird build failures, like

    error: failed to select a version for the requirement `arbitrary = "^1.0.0"` (locked to 1.1.3)
    candidate versions found which didn't match: 1.1.1
    location searched: directory source `/home/vagrant/build/srclib/MozFennec/third_party/rust` (which is replacing registry `crates-io`)
    required by package `gluesmith v0.1.0 (/home/vagrant/build/srclib/MozFennec/js/src/fuzz-tests/gluesmith)`
    perhaps a crate was updated and forgotten to be re-vendored?
    gmake[3]: *** [backend.mk:115: config/.deps/cbindgen-metadata.json.stub] Error 101